version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-univer
    environment:
      POSTGRES_DB: univerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db/init-keycloak-db.sql:/docker-entrypoint-initdb.d/init-keycloak-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-univer
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak        # Явно указываем имя БД
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8082
    command: ["start-dev"]
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

volumes:
  postgres_data: