server:
  port: 8023

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/univerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/univer-realm

  flyway:
    enabled: true
    baseline-on-migrate: true  # Полезно, если БД уже существует
    locations: classpath:db/migration/schema,classpath:db/migration/data

# SpringDoc / OpenAPI
springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    oauth:
      client-id: univer-client
      client-secret: univer-client-secret
      realm: univer-realm
      app-name: University API
      scope-separator: " "
      scopes: openid

# Keycloak Config
keycloak:
  enabled: true
  realm: univer-realm
  auth-server-url: http://localhost:8082
  ssl-required: external
  resource: univer-client
  use-resource-role-mappings: true
  bearer-only: true
  admin:
    username: admin
    password: admin
    client-id: univer-client